joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

/gazebo_ros_control:
    pid_gains:
        joint_right_wheel:
            p: 2.05
            i: 1.3
            d: 0.0

        joint_left_wheel:
            p: 2.05
            i: 1.3
            d: 0.0